name: hearthstone_json_api
description: A starting point for Dart libraries or applications.
version: 0.0.1
homepage: https://github.com/jacob-shuman/hearthstone_json_api
author: Jacob Shuman <jacob.shuman7@gmail.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
